In [1]:
from design.mockups.db.analysis import load_metrics
from datetime import datetime
import pandas as pd
import sqlite3 as sql
from contextlib import closing
from dotenv import load_dotenv
import os

In [2]:
load_dotenv()

True

In [3]:
DB_PATH = os.environ["DB_PATH"]

In [4]:
with closing(sql.connect(DB_PATH)) as conn:
    mood = load_metrics(conn, 2, "Mood", "US/Pacific")
    quark = load_metrics(conn, 2, "Quark", "US/Pacific")
    meditate = load_metrics(conn, 2, "Meditate", "US/Pacific")
    water = load_metrics(conn, 2, "Water", "US/Pacific")
    weight = load_metrics(conn, 2, "Weight", "US/Pacific")
    exercise = load_metrics(conn, 2, "Exercise", "US/Pacific")

In [5]:
today = pd.Timestamp.now(tz="US/Pacific").normalize()
today

Timestamp('2026-03-09 00:00:00-0700', tz='US/Pacific')

In [6]:
one_week_ago = today - pd.DateOffset(days=6)
one_week_ago

Timestamp('2026-03-03 00:00:00-0800', tz='US/Pacific')

In [7]:
all_days = pd.date_range(one_week_ago, today, freq="D")
all_days

DatetimeIndex(['2026-03-03 00:00:00-08:00', '2026-03-04 00:00:00-08:00',
               '2026-03-05 00:00:00-08:00', '2026-03-06 00:00:00-08:00',
               '2026-03-07 00:00:00-08:00', '2026-03-08 00:00:00-08:00',
               '2026-03-09 00:00:00-07:00'],
              dtype='datetime64[us, US/Pacific]', freq='D')

In [8]:
recent_weight = weight[weight["recorded_at"] >= one_week_ago]
recent_weight

                  recorded_at  value
100 2026-03-04 13:57:41-08:00  129.0
101 2026-03-05 22:41:44-08:00  179.0
102 2026-03-06 11:49:33-08:00  192.0
103 2026-03-07 15:00:21-08:00  171.0

In [9]:
recent_weight["value"].mean()

np.float64(167.75)

In [10]:
recent_weight.resample("D", on="recorded_at").mean().dropna().reindex(all_days, fill_value=0)

                           value
2026-03-03 00:00:00-08:00    0.0
2026-03-04 00:00:00-08:00  129.0
2026-03-05 00:00:00-08:00  179.0
2026-03-06 00:00:00-08:00  192.0
2026-03-07 00:00:00-08:00  171.0
2026-03-08 00:00:00-08:00    0.0
2026-03-09 00:00:00-07:00    0.0

In [11]:
last_mood = mood.tail(1).values[0][1]
last_mood

'Angry'

In [12]:
mood.head(10)

                 recorded_at   value
1  2026-02-07 16:02:34-08:00  Serene
2  2026-02-07 19:54:22-08:00  Serene
3  2026-02-08 10:50:07-08:00   Angry
4  2026-02-08 11:37:19-08:00  Serene
5  2026-02-08 14:10:19-08:00     Sad
6  2026-02-09 11:33:57-08:00   Angry
7  2026-02-09 12:11:58-08:00  Serene
8  2026-02-10 15:00:10-08:00  Serene
9  2026-02-11 17:52:05-08:00   Happy
10 2026-02-11 21:58:14-08:00   Angry

In [14]:
recent_angry = mood[(mood["value"] == last_mood) & (mood["recorded_at"] >= one_week_ago)]
recent_angry

                 recorded_at  value
50 2026-03-04 06:54:41-08:00  Angry
59 2026-03-07 16:58:33-08:00  Angry
61 2026-03-08 17:04:33-07:00  Angry
63 2026-03-08 22:40:23-07:00  Angry

In [16]:
recent_angry.resample("D", on="recorded_at").size()

recorded_at
2026-03-04 00:00:00-08:00    1
2026-03-05 00:00:00-08:00    0
2026-03-06 00:00:00-08:00    0
2026-03-07 00:00:00-08:00    1
2026-03-08 00:00:00-08:00    2
Freq: D, dtype: int64

In [18]:
recent_angry.resample("D", on="recorded_at").size().reindex(all_days, fill_value=0).values

array([0, 1, 0, 0, 1, 2, 0])

In [ ]:
recent_meditate = meditate[meditate["recorded_at"] >= one_week_ago]
recent_meditate

In [ ]:
recent_meditate.resample("D", on="recorded_at").size()

In [ ]:
recent_meditate.resample("D", on="recorded_at").size().reindex(all_days, fill_value=0)